parameters:
    bank_group: "Client"
    dev_group: "Dev"

services:
    sonata.admin.card:
        class: Bank\MainBundle\Admin\CardAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%bank_group%", label: "Card", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Bank\MainBundle\Entity\Card
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminCard]]

    sonata.admin.client:
        class: Bank\MainBundle\Admin\ClientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%bank_group%", label: "Client", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Bank\MainBundle\Entity\Client
            - BankMainBundle:CRUD
        calls:
            - [ setTranslationDomain, [SonataAdminClient]]

    sonata.admin.account:
        class: Bank\MainBundle\Admin\AccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%bank_group%", label: "Account", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Bank\MainBundle\Entity\Account
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminAccount]]

    sonata.admin.currency:
        class: Bank\MainBundle\Admin\CurrencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%bank_group%", label: "Currency", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Bank\MainBundle\Entity\Currency
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminCurrency]]

    sonata.admin.eripCategory:
        class: Bank\MainBundle\Admin\EripCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%bank_group%", label: "Erip Category", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Bank\MainBundle\Entity\EripCategory
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminEripCategory]]

    sonata.admin.eripPayment:
        class: Bank\MainBundle\Admin\EripPaymentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%bank_group%", label: "Erip Payment", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Bank\MainBundle\Entity\EripPayment
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminEripPayment]]

    sonata.admin.eripPaymentField:
        class: Bank\MainBundle\Admin\EripPaymentFieldAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%dev_group%", label: "Erip Payment Field", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Bank\MainBundle\Entity\EripPaymentField
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminEripPaymentField]]

    subscriber.client:
        class: Bank\MainBundle\Services\ClientSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber, connection: default }


    localizator:
        class: Bank\MainBundle\Services\Localizator
        arguments: [%locales%]
