Bank\MainBundle\Entity\Account:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        balance:
            type: float
        isActive:
            type: boolean

    manyToOne:
        client:
            targetEntity: Client
            inversedBy: accounts
        currency:
            targetEntity: Currency

    oneToMany:
        cards:
            targetEntity: Card
            mappedBy: account
            cascade: [persist]

    lifecycleCallbacks: {  }
