Bank\MainBundle\Entity\Account:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        currency:
            type: string
            length: 255
        balance:
            type: float

    manyToOne:
        client:
            targetEntity: Client
            inversedBy: accounts

    lifecycleCallbacks: {  }
