Bank\MainBundle\Entity\AutoPayment:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        startDate:
            type: datetime
        period:
            type: string
            length: 20
        type:
            type: string
            length: 20
        data:
            type: json_array
        lastPayment:
            type: datetime
            nullable: true

    manyToOne:
        account:
            targetEntity: Account

    lifecycleCallbacks: {  }
