Bank\MainBundle\Entity\EripCategory:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: json_array

    oneToMany:
        payments:
            targetEntity: EripPayment
            mappedBy: category
    lifecycleCallbacks: {  }
