Bank\MainBundle\Entity\EripPaymentField:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        text:
            type: string
            length: 255
        regex:
            type: string
            length: 255

    manyToOne:
        payment:
            targetEntity: EripPayment
            inversedBy: fields
    lifecycleCallbacks: {  }
