bank_api_client_list:
    pattern:  /client/list/{id}
    defaults: { _controller: BankApiBundle:Client:list, _format: ~ }
    requirements:
        _method: POST

bank_api_client_auth:
    pattern:  /client/auth
    defaults: { _controller: BankApiBundle:Client:auth, _format: ~ }
    requirements:
        _method: POST

bank_api_client_changePassword:
    pattern:  /client/changePassword
    defaults: { _controller: BankApiBundle:Client:changePassword, _format: ~ }
    requirements:
        _method: POST

bank_api_erip_tree:
    pattern:  /erip/tree
    defaults: { _controller: BankApiBundle:Erip:tree, _format: ~ }
    requirements:
        _method: POST

bank_api_erip_pay:
    pattern:  /erip/pay
    defaults: { _controller: BankApiBundle:Erip:pay, _format: ~ }
    requirements:
        _method: POST

bank_api_payment_pay:
    pattern:  /payment/pay
    defaults: { _controller: BankApiBundle:Payment:pay, _format: ~ }
    requirements:
        _method: POST
